dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $APP_NAME .
      - docker images
      - docker tag $APP_NAME $DOCKER_USERNAME/$APP_NAME
      - docker push $DOCKER_USERNAME/$APP_NAME